# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidget, QMainWindow, QApplication, QComboBox



class Prioritet(QComboBox):
    def __init__(self, parent = None, row = 0, main_window = None):
        super().__init__(parent)
        self.row_index = row
        self.main_window = main_window

        self.addItems(['Низкий', 'Средний', 'Высокий'])

        self.currentIndexChanged.connect(self.prioritet_changed)


    def prioritet_changed(self):
        if self.main_window:
            self.main_window.ui.update_icon(self.row_index, self.currentText())

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 40, 401, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setup_prioritet(self, main_window):
        self.prioritet_colors = {
            'Низкий': QtGui.QColor('green'),
            'Средний': QtGui.QColor('yellow'),
            'Высокий': QtGui.QColor('red')
        }
        for row in range(self.tableWidget.rowCount()):
            combo = Prioritet(self.tableWidget, row, main_window)
            self.tableWidget.setCellWidget(row, 1, combo)

            self.update_icon(row, combo.currentText())

    def update_icon(self, row, prioritet_text):
        pixmap = QtGui.QPixmap(32, 32)
        pixmap.fill(QtGui.QColor('transparent'))

        painter = QtGui.QPainter(pixmap)
        painter.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)

        color = self.prioritet_colors.get(prioritet_text)
        painter.setBrush(QtGui.QBrush(color))

        painter.setPen(QtGui.QPen(QtGui.QColor('black'), 1))
        painter.drawEllipse(4, 4, 24, 24)

        painter.end()
        icon_item = self.tableWidget.item(row, 0)
        if icon_item is None:
            icon_item = QtWidgets.QTableWidgetItem()
            icon_item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.tableWidget.setItem(row, 0, icon_item)
        icon_item.setIcon(QtGui.QIcon(pixmap))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Приоритет"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Задача"))



class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.setup_prioritet(self)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())