# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTreeWidget, QMainWindow, QApplication, QLayout, QVBoxLayout, QLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(5, -1, 501, 401))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.widget)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget)
        self.stackedWidget.setObjectName("stackedWidget")

        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        layout = QVBoxLayout(self.page)
        label = QLabel('Общие настройки системы')
        layout.addWidget(label)
        layout.addWidget(QLabel('Настройки системы'))
        layout.addStretch()
        self.stackedWidget.addWidget(self.page)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        layout2 = QVBoxLayout(self.page_2)
        label2 = QLabel('Общие настройки системы')
        layout2.addWidget(label2)
        layout2.addWidget(QLabel('Настри системы'))
        layout2.addStretch()
        self.stackedWidget.addWidget(self.page_2)

        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        layout3 = QVBoxLayout(self.page_3)
        label3 = QLabel('Общие настройки системы')
        layout3.addWidget(label3)
        layout3.addWidget(QLabel('Настройки сы'))
        layout3.addStretch()
        self.stackedWidget.addWidget(self.page_3)

        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        layout4 = QVBoxLayout(self.page_4)
        label4 = QLabel('Общие настройки системы')
        layout4.addWidget(label4)
        layout4.addWidget(QLabel('Настройк'))
        layout4.addStretch()
        self.stackedWidget.addWidget(self.page_4)

        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.treeWidget.setFixedWidth(150)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Настройки"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Система"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "дисплей"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Устройства"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "О компьютере"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)



class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)


        self.ui.treeWidget.itemClicked.connect(self.treeClicked)

    def treeClicked(self, item):
        if item == self.ui.treeWidget.topLevelItem(0):
            self.ui.stackedWidget.setCurrentIndex(0)
        if item == self.ui.treeWidget.topLevelItem(0).child(0):
            self.ui.stackedWidget.setCurrentIndex(1)
        if item == self.ui.treeWidget.topLevelItem(1):
            self.ui.stackedWidget.setCurrentIndex(2)
        if item == self.ui.treeWidget.topLevelItem(2):
            self.ui.stackedWidget.setCurrentIndex(3)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
