# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap, QPainter
from PyQt6.QtWidgets import (QMainWindow, QApplication, QTableWidget,
                             QTableWidgetItem, QFileDialog, QStyledItemDelegate,
                             QStyleOptionViewItem)
from PyQt6.QtCore import Qt, QSize


class ImageDelegate(QStyledItemDelegate):
    def paint(self, painter, option, index):
        if index.data(Qt.ItemDataRole.DecorationRole):
            pixmap = index.data(Qt.ItemDataRole.DecorationRole)
            if pixmap and isinstance(pixmap, QPixmap):
                pixmap = pixmap.scaled(
                    option.rect.width() - 4,
                    option.rect.height() - 4,
                    Qt.AspectRatioMode.KeepAspectRatio,
                    Qt.TransformationMode.SmoothTransformation
                )
                x = option.rect.center().x() - pixmap.width() // 2
                y = option.rect.center().y() - pixmap.height() // 2

                painter.drawPixmap(x, y, pixmap)
        else:
            super().paint(painter, option, index)

    def sizeHint(self, option, index):
        return QSize(100, 100)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 50, 751, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(5)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сотрудники"))

        self.tableWidget.horizontalHeaderItem(0).setText(_translate("MainWindow", "Фамилия"))
        self.tableWidget.horizontalHeaderItem(1).setText(_translate("MainWindow", "Имя"))
        self.tableWidget.horizontalHeaderItem(2).setText(_translate("MainWindow", "Отчество"))
        self.tableWidget.horizontalHeaderItem(3).setText(_translate("MainWindow", "Фото"))

        self.tableWidget.setRowHeight(0, 100)
        self.tableWidget.setRowHeight(1, 100)
        self.tableWidget.setRowHeight(2, 100)
        self.tableWidget.setRowHeight(3, 100)
        self.tableWidget.setRowHeight(4, 100)


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.image_delegate = ImageDelegate()
        self.ui.tableWidget.setItemDelegateForColumn(3, self.image_delegate)
        self.ui.tableWidget.cellDoubleClicked.connect(self.on_cell_double_clicked)


    def on_cell_double_clicked(self, row, column):
        if column == 3:
            file_path, _ = QFileDialog.getOpenFileName(
                self)

            if file_path and os.path.exists(file_path):
                pixmap = QPixmap(file_path)
                if not pixmap.isNull():
                    thumbnail = pixmap.scaled(
                        80, 80,
                        Qt.AspectRatioMode.KeepAspectRatio,
                        Qt.TransformationMode.SmoothTransformation
                    )

                    item = QTableWidgetItem()
                    item.setData(Qt.ItemDataRole.DecorationRole, thumbnail)
                    item.setData(Qt.ItemDataRole.UserRole,
                                 file_path)
                    self.ui.tableWidget.setItem(row, column, item)

                    self.ui.tableWidget.viewport().update()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())