# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Корзина"))


import sys
from PyQt6.QtWidgets import (
    QMainWindow, QApplication, QTableWidgetItem,
    QPushButton, QMessageBox, QHBoxLayout, QWidget
)


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        # Загружаем интерфейс из Qt Designer
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Настраиваем таблицу
        self.setup_table()

        # Заполняем таблицу тестовыми данными
        self.fill_table()

    def setup_table(self):
        # Устанавливаем заголовки столбцов
        headers = ["Товар", "Цена", "Количество", "Удалить"]
        self.ui.tableWidget.setHorizontalHeaderLabels(headers)

        # Настраиваем ширину столбцов
        self.ui.tableWidget.horizontalHeader().setStretchLastSection(True)

    def fill_table(self):
        # Тестовые данные
        products = [
            ["Ноутбук", "45000", "1"],
            ["Мышь", "1500", "2"],
            ["Клавиатура", "3200", "1"],
            ["Монитор", "21000", "1"],
            ["Наушники", "5400", "1"]
        ]

        # Заполняем таблицу
        for row, product in enumerate(products):
            for col in range(3):  # Первые 3 столбца
                item = QTableWidgetItem(product[col])
                if col in [1, 2]:  # Числовые столбцы
                    item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
                self.ui.tableWidget.setItem(row, col, item)

            self.add_delete_button(row)

    def add_delete_button(self, row):
        delete_button = QPushButton("✕")
        delete_button.setStyleSheet("""
            QPushButton {
                background-color: red;
                color: white;
                border: none;
                border-radius: 10px;
                font-size: 14px;
                font-weight: bold;
                width: 20px;
                height: 20px;
            }
            QPushButton:hover {
                background-color: #ff4444;
            }
        """)

        delete_button.clicked.connect(self.delete_item(row))

        widget = QWidget()
        layout = QHBoxLayout(widget)
        layout.addWidget(delete_button)
        layout.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.setContentsMargins(0, 0, 0, 0)

        self.ui.tableWidget.setCellWidget(row, 3, widget)

    def delete_item(self, row):
        product_name = self.ui.tableWidget.item(row, 0).text()

        reply = QMessageBox.question(
            self,
            "Подтверждение удаления",
            f"Вы уверены, что хотите удалить товар: {product_name}?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.No
        )

        if reply == QMessageBox.StandardButton.Yes:
            self.ui.tableWidget.removeRow(row)

            QMessageBox.information(
                self,
                "Успешно",
                "Товар удален из корзины"
            )


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
