# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QApplication, QStyledItemDelegate
from PyQt6.QtGui import QUndoCommand, QUndoStack, QKeySequence


class ItemDelegate(QStyledItemDelegate):
    def displayText(self, value, locale):
        if value.isdigit():
            size_bytes = int(value)
            return self.format_size(size_bytes)
        return value

    def format_size(self, size_bytes):
        for unit in ['Б', 'КБ', 'МБ', 'ГБ', 'ТБ']:
            if size_bytes < 1024.0:
                return f'{size_bytes:.1f}{unit}'
            size_bytes /= 1024
        return f'{size_bytes:.1f}ТБ'


class TableEditCommand(QUndoCommand):
    def __init__(self, table, row, column, old_value, new_value):
        super().__init__()
        self.table = table
        self.row = row
        self.column = column
        self.old_value = old_value
        self.new_value = new_value

    def undo(self):
        item = self.table.item(self.row, self.column)
        if item:
            item.setText(self.old_value)

    def redo(self):
        item = self.table.item(self.row, self.column)
        if item:
            item.setText(self.new_value)
        else:
            item = QtWidgets.QTableWidgetItem(self.new_value)
            self.table.setItem(self.row, self.column, item)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 60, 300, 350))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(5)

        self.undoButton = QtWidgets.QPushButton("Undo (Ctrl+Z)", parent=self.centralwidget)
        self.undoButton.setGeometry(QtCore.QRect(50, 20, 120, 30))

        self.redoButton = QtWidgets.QPushButton("Redo (Ctrl+Y)", parent=self.centralwidget)
        self.redoButton.setGeometry(QtCore.QRect(180, 20, 120, 30))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Table Editor"))

        self.tableWidget.setHorizontalHeaderLabels(["Документ", "Размер"])

        data = [
            ["Документ1.txt", "1024"],
            ["Документ2.txt", "1048576"],
            ["Документ3.txt", "5368709120"],
            ["Документ4.txt", "2048"],
            ["Документ5.txt", "555"]
        ]

        for row, row_data in enumerate(data):
            for col, text in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(text)
                self.tableWidget.setItem(row, col, item)


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Инициализируем стек undo/redo
        self.undo_stack = QUndoStack(self)

        # Устанавливаем делегат для форматирования размера
        item_delegate = ItemDelegate()
        self.ui.tableWidget.setItemDelegateForColumn(1, item_delegate)

        # Подключаем сигналы кнопок
        self.ui.undoButton.clicked.connect(self.undo)
        self.ui.redoButton.clicked.connect(self.redo)

        # Подключаем горячие клавиши
        QtGui.QShortcut(QKeySequence("Ctrl+Z"), self).activated.connect(self.undo)
        QtGui.QShortcut(QKeySequence("Ctrl+Y"), self).activated.connect(self.redo)

        # Подключаем сигнал изменения ячейки
        self.ui.tableWidget.itemChanged.connect(self.on_item_changed)

        # Обновляем состояние кнопок
        self.undo_stack.canUndoChanged.connect(self.ui.undoButton.setEnabled)
        self.undo_stack.canRedoChanged.connect(self.ui.redoButton.setEnabled)

        # Отключаем кнопки при запуске
        self.ui.undoButton.setEnabled(False)
        self.ui.redoButton.setEnabled(False)

        # Сохраняем начальные значения
        self.old_values = {}

    def on_item_changed(self, item):
        # Получаем текущее значение
        new_value = item.text()

        # Получаем старое значение из кэша или пустую строку
        key = (item.row(), item.column())
        old_value = self.old_values.get(key, "")

        # Если значение изменилось
        if old_value != new_value:
            # Создаем команду undo/redo
            command = TableEditCommand(self.ui.tableWidget, item.row(), item.column(), old_value, new_value)
            self.undo_stack.push(command)

            # Обновляем кэш
            self.old_values[key] = new_value

    def undo(self):
        self.undo_stack.undo()

    def redo(self):
        self.undo_stack.redo()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())