# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QApplication



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 210, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Поменять"))

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.dark_theme = False
        self.set_light_theme()
        self.ui.pushButton.clicked.connect(self.theme)

    def set_dark_theme(self):
        dark_stylesheet = """
               QMainWindow, QWidget {
                   background-color: #353535;
                   color: #ffffff;
               }
               QPushButton {
                   background-color: #454545;
                   color: white;
                   border: 2px solid #555555;
                   border-radius: 5px;
                   padding: 10px;
                   font-size: 14pt;
               }
               QPushButton:hover {
                   background-color: #555555;
               }
               QPushButton:pressed {
                   background-color: #252525;
               }
               """

        self.setStyleSheet(dark_stylesheet)

    def set_light_theme(self):
        self.setStyleSheet("")
    def theme(self):
        if self.dark_theme:
            self.set_light_theme()
        else:
            self.set_dark_theme()
        self.dark_theme = not self.dark_theme

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
