# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import random
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QApplication, QItemDelegate, QStyledItemDelegate, QStyleOptionProgressBar
from PyQt6.QtCore import Qt, QTimer


class ItemDelegate(QStyledItemDelegate):
    def displayText(self, value, locale):
        if value.isdigit():
            size_bytes = int(value)
            return self.format_size(size_bytes)
        return value

    def format_size(self, size_bytes):
        for unit in ['Б', 'КБ', 'МБ', 'ГБ', 'ТБ']:
            if size_bytes < 1024.0:
                return f'{size_bytes:.1f}{unit}'
            size_bytes /= 1024


class ProgressBarDelegate(QStyledItemDelegate):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.progress_values = {}

    def paint(self, painter, option, index):
        if index.column() == 2:  # Только для колонки с прогрессом
            progress = self.get_progress_value(index)

            # Настраиваем прогресс-бар
            progress_bar_option = QStyleOptionProgressBar()
            progress_bar_option.rect = option.rect
            progress_bar_option.minimum = 0
            progress_bar_option.maximum = 100
            progress_bar_option.progress = progress
            progress_bar_option.text = f"{progress}%"
            progress_bar_option.textVisible = True
            progress_bar_option.state = option.state

            # Рисуем прогресс-бар
            QtWidgets.QApplication.style().drawControl(
                QtWidgets.QStyle.ControlElement.CE_ProgressBar,
                progress_bar_option,
                painter
            )
        else:
            super().paint(painter, option, index)

    def get_progress_value(self, index):
        # Получаем значение прогресса из кэша или генерируем случайное
        key = (index.row(), index.column())
        if key not in self.progress_values:
            self.progress_values[key] = random.randint(0, 100)
        return self.progress_values[key]

    def sizeHint(self, option, index):
        if index.column() == 2:
            return QtCore.QSize(150, 30)
        return super().sizeHint(option, index)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 60, 800, 700))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.tableWidget.setFixedHeight(400)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Документ"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Размер"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Документ1.txt"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "1024"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Документ2.txt"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "1048576"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Документ3.txt"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "5368709120"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Документ4.txt"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "2048"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Документ5.txt"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "555"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        item_delegate = ItemDelegate(self.ui.tableWidget)
        self.ui.tableWidget.setItemDelegateForColumn(1, item_delegate)
        progress_delegate = ProgressBarDelegate(self.ui.tableWidget)
        self.ui.tableWidget.setItemDelegateForColumn(2, progress_delegate)



if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())